import { groupsReverse } from 'common/data/informalGroups';

const filters = {
  'amphibians and reptiles': [groupsReverse.amphibian, groupsReverse.reptile],
  birds: [groupsReverse.bird],
  fish: [
    groupsReverse['bony fish'],
    groupsReverse['cartilagenous fish'],
    groupsReverse['jawless fish'],
    groupsReverse.lancelet,
  ],
  'fungi and slime moulds': [
    groupsReverse.fungoid,
    groupsReverse.fungus,
    groupsReverse['slime mould'],
  ],
  insects: {
    'ants, bees, sawflies, wasps': [groupsReverse.hymenopteran],
    beetles: [groupsReverse.beetle],
    butterflies: [groupsReverse.butterfly],
    'dragonflies and damselflies': [groupsReverse.dragonfly],
    'grasshoppers and allies': [
      groupsReverse.cockroach,
      groupsReverse.earwig,
      groupsReverse.mantis,
      groupsReverse.orthopteran,
      groupsReverse['stick insect'],
    ],
    moths: [groupsReverse.moth],
    'other insect groups': [
      groupsReverse.alderfly,
      groupsReverse.booklouse,
      groupsReverse.bristletail,
      groupsReverse.flea,
      groupsReverse.lacewing,
      groupsReverse.louse,
      groupsReverse.proturan,
      groupsReverse['scorpion fly'],
      groupsReverse.silverfish,
      groupsReverse.snakefly,
      groupsReverse.springtail,
      groupsReverse.stylops,
      groupsReverse.thrips,
      groupsReverse['two-tailed bristletail'],
      groupsReverse['web-spinner'],
    ],
    riverflies: [
      groupsReverse['caddis fly'],
      groupsReverse.mayfly,
      groupsReverse.stonefly,
    ],
    'true bugs and hoppers': [groupsReverse['true bug']],
    'true flies': [groupsReverse['true fly']],
  },
  invertebrates: {
    'centipedes, millipedes': [
      groupsReverse.centipede,
      groupsReverse.millipede,
      groupsReverse.pauropod,
      groupsReverse.symphylan,
    ],
    crustaceans: [groupsReverse.crustacean],
    molluscs: [groupsReverse.mollusc],
    'other invertebrate groups': [
      groupsReverse.bryozoan,
      groupsReverse.coelenterate,
      groupsReverse['comb jelly'],
      groupsReverse.echinoderm,
      groupsReverse.entoproct,
      groupsReverse.lampshell,
      groupsReverse.loriciferan,
      groupsReverse.mesozoan,
      groupsReverse.monogenean,
      groupsReverse['mud dragon'],
      groupsReverse.rotifer,
      groupsReverse['sea spider'],
      groupsReverse.sponge,
      groupsReverse.tunicate,
      groupsReverse.waterbear,
    ],
    'spiders, harvestmen and other arachnids': [
      groupsReverse.acarine,
      groupsReverse['false scorpion'],
      groupsReverse.harvestman,
      groupsReverse.scorpion,
      groupsReverse.spider,
    ],
    worms: [
      groupsReverse['acorn worm'],
      groupsReverse.annelid,
      groupsReverse['arrow worm'],
      groupsReverse.beardworm,
      groupsReverse.flatworm,
      groupsReverse.gnathostomulid,
      groupsReverse.hairworm,
      groupsReverse['horseshoe worm'],
      groupsReverse['peanut worm'],
      groupsReverse.priapulid,
      groupsReverse['ribbon worm'],
      groupsReverse.roundworm,
      groupsReverse['spoon worm'],
      groupsReverse.tapeworm,
      groupsReverse['thorny-headed worm'],
      groupsReverse.trematode,
    ],
  },
  lichens: [groupsReverse.lichen],
  mammals: [groupsReverse.mammal, groupsReverse['marine mammal']],
  'other groups': [
    groupsReverse.bacterium,
    groupsReverse.chromist,
    groupsReverse.cyanobacterium,
    groupsReverse.cycliophoran,
    groupsReverse.foraminiferan,
    groupsReverse.gastrotrich,
    groupsReverse.protozoan,
    groupsReverse.unassigned,
    groupsReverse.undetermined,
  ],
  plants: {
    'vascular plants': [
      groupsReverse.clubmoss,
      groupsReverse.conifer,
      groupsReverse.fern,
      groupsReverse['flower. plant'],
      groupsReverse.ginkgo,
      groupsReverse.horsetail,
      groupsReverse.quillwort,
      groupsReverse.stonewort,
    ],
    algae: [groupsReverse.alga, groupsReverse.diatom],
    'mosses and relatives': [
      groupsReverse.hornwort,
      groupsReverse.liverwort,
      groupsReverse.moss,
    ],
  },
} as const;

export default filters;
